### ISSUE TITLE
sets all titles to japan

### ISSUE THREAD

**Issue by catfatwm** [DarkSynopsis/LumaLocaleRegionAutoSetter#1]
luma 9.1: when i run it, it sets all my regions to japan

**Comment by DarkSynopsis** [comment]
I've ran this on 4 different 3DS devices, mix of models, O3DS, 2DS and N3DS and not had this happen, even going back over the code I can't see why it would.

Is it creating text files for the US/EU TitleIDs? I mean if it is it shouldn't be possible for them to have JPN within the file.

**Comment by catfatwm** [comment]
i think i know what happened: it made all my injections jpn. i saw a bunch of jpn, panicked, knowing i have one game that this would be useful for, and was just testing it.

**Comment by DarkSynopsis** [comment]
Ah, it just creates locale files for all the TitleIDs I have setup, it doesn't check your 3DS for what is installed, it shouldn't cause any issues have locale files for games you don't have installed but if you did in the future it would be good to go.

**Comment by catfatwm** [comment]
ah ok, sorry for wasting your time, and i appreciate it, its obvious i have no idea what im talking about. i like to look for new titles from titledb/reddit and test everything, and often i have no idea what im testing or what it should do, anyways, thanks.
