### ISSUE TITLE
Install Explanation

### ISSUE THREAD

**Issue by JoatMasterofNun** [DarkSynopsis/LumaLocaleRegionAutoSetter#3]
The readme is unclear. Homebrew will run that .c file?

**Comment by JoatMasterofNun** [comment]
As in, I maybe mildly retarded. After reading through your code, appears most of the files are all needed for the build. I'm just not figuring out how to execute the "run the homebrew" portion of it.

**Comment by DarkSynopsis** [comment]
? Head to the releases tab and install the CIA or use the 3dsx via the Homebrew Launcher.

**Comment by JoatMasterofNun** [comment]
Oh dear god, I am retarded. It never occurred to me to click that. Honestly I don't think I've ever had to because a link was already pointed there or all the files were on the home(?) page (where you can clone or download git). Here I was thinking like, "how to run C program on homebrew".

Thank you.
